name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Branch, den du deployen willst

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Raspberry Pi and pull
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_KEY }}
          script: |
            cd /var/www/website
            git pull
            sudo systemctl reload nginx
